Etape 2: Affichage de la table des sections
KatSukiFireStar/L3_Info_Groupe_15_Projet_Prog5 pull request #20
Opened 2022-12-16 09:01 UTC by ZPyrolink

2022-12-16 09:40 UTC, KatSukiFireStar requested changes
Changer les else

2022-12-16 10:29 UTC, KatSukiFireStar commented on elfFile.c
> +Elf32_Shdr *ShowSectionTableAndDetails(FILE *elfFile, Elf32_Ehdr header){
Rechercher dans le header la table des string pour afficher les noms a partir du sh_name

2022-12-16 10:38 UTC, KatSukiFireStar commented on elfFile.c
> +Elf32_Shdr *ShowSectionTableAndDetails(FILE *elfFile, Elf32_Ehdr header){
Faire un affichage dans l'ordre suivant:
Nom
Type
Adresse
Décalage
Taille
TaillEntre
Fanion
Lien
Info
Alignement

2022-12-16 10:39 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("Section: %ls\n", &sectionTable[i].sh_name);
ne pas print la valeur mais la chercher dans la table des string et afficher le nom

2022-12-16 12:19 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("Taille de la section : %d\n", sectionTable[i].sh_size);
ne pas l'afficher en %d mais %x c'est une valeur hexa

2022-12-16 12:20 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("Type de la section : %d\n", sectionTable[i].sh_type);
ne pas afficher la valeur du type mais le nom en regardant dans la doc elf p 25/106

2022-12-16 12:22 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("Position de la section : %d\n", sectionTable[i].sh_offset);
encore une fois le decalage est une valeur hexa mettre %x

2022-12-16 12:29 UTC, KatSukiFireStar commented on elfFile.c
> +
pour les flags ecrire quelque chose de la forme 
Fanions: AX
A -> Allocation
X -> execution
W -> ecriture
M -> fusion

2022-12-16 12:30 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("Adresse de la section : %d\n", sectionTable[i].sh_addr);
%x

2022-12-16 12:31 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("Décalage de la section : %d\n", sectionTable[i].sh_offset);
deja afficher plus haut

2022-12-16 12:41 UTC, KatSukiFireStar commented on elfFile.c
> +        printf("La taille de l'entrée, pour les sections qui contiennent une table d'entrées de même taille : %d\n", sectionTable[i].sh_entsize);
%x

2022-12-16 22:18 UTC, ZPyrolink commented on elfFile.c
> +            rewind(elfFile);//OU fseek(elfFile, sectionTable[i].sh_offset, SEEK_SET);
`rewind(elfFile);` est différent de `fseek(elfFile, sectionTable[i].sh_offset, SEEK_SET);` !

2022-12-16 22:18 UTC, ZPyrolink commented on elfFile.c
> +
Une fois que tu as écrit chaque flags, indique à quoi ils correspondent. Un peu comme a fait @mhamadhajj

2022-12-16 22:18 UTC, ZPyrolink commented on elfFile.c
> +
Il faudrait aussi rajouter la signification de chaque flags appliqués. On peut faire comme @mhamadhajj et juste afficher la valeur hexa puis expliquer ce que ça signifie entre paranthèse après.

2022-12-16 22:20 UTC, ZPyrolink commented on elfFile.c
> +            case 0:
Utiliser les macros plutôt que les valeurs en dur

2022-12-16 22:20 UTC, ZPyrolink commented on elfFile.c
> +        printf("Taille de la section : %d\n", sectionTable[i].sh_size);
Non, les tailles sont à afficher en entier (on part d'un offset 0x... et on lit Y bytes)

2022-12-16 22:26 UTC, ZPyrolink commented on elfFile.c
> +        printf("Taille de la section : %x\n", sectionTable[i].sh_size);
Remettre %d à la place de %x. Voir https://github.com/KatSukiFireStar/L3_Info_Groupe_15_Projet_Prog5/pull/20#discussion_r1051205990

2022-12-16 22:26 UTC, ZPyrolink commented on elfFile.c
> +        printf("Nom de la section : %s\n", sectionTable[i].sh_name);
Il faut utiliser la table des strings. On pourra t'expliquer vite fais avec @KatSukiFireStar 
Voir https://github.com/KatSukiFireStar/L3_Info_Groupe_15_Projet_Prog5/pull/20#discussion_r1050598262 et https://github.com/KatSukiFireStar/L3_Info_Groupe_15_Projet_Prog5/pull/20#discussion_r1050590001

2022-12-19 14:42 UTC, KatSukiFireStar approved these changes

2022-12-19 14:42 UTC, KatSukiFireStar commented on elfFile.c
> +
ajouter \0 a la fin du nom

2022-12-19 14:42 UTC, merged