Mohammad hajj
KatSukiFireStar/L3_Info_Groupe_15_Projet_Prog5 pull request #21
Opened 2022-12-16 10:23 UTC by mhamadhajj

affichage en-tête (modifié)

2022-12-16 13:21 UTC, ZPyrolink requested changes

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +        printf("%c " , header.e_ident[i]);
Remplace %c par %x

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    if(header.e_ident[4]==1)
Plutôt que les valeurs, utiliser les macros (EI_CLASS, ELFCLASS32, ELFCLASS64, etc...)

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("\nClasse : \t");
Remplacer "Classe" par "Data"

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    if(header.e_ident[5]==1)
Macros

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("Version: \t %d",header.e_ident[6]);
Macro

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("\nVersion ABI : \t");
Remplacer affichage (Version ABI : %value (%v))
%value = valeur de e_version
%v = Invalid / Current Version

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    if(header.e_version==0)
Macro (EV_NONE, EV_CURRENT)

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("machine : \t");
En double !

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("Version ABI : \t");
En double !

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("Entry point address :  \t%d\n",header.e_entry);
Replacer %d par %x

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +    printf("Start of section headers :  \t%d\n",header.e_phoff);
Remplacer e_phoff par e_shoff

2022-12-16 13:21 UTC, ZPyrolink commented on elfFile.c
> +        printf("X, Trap nil pointer dereference");
Enlever X,

2022-12-16 21:46 UTC, ZPyrolink requested changes
Le problème venait en effet du fait qu'on utilisait un fichier 64bit et non 32bit mais il reste encore quelques / coquilles à corriger.
Essaye aussi de, soit tout mettre en anglais, soit tout en français (il faudra se mettre d'accord avec tout le monde, mais je crois qu'on est principalement parti sur le français)
Est-ce qu'on ne rajouterai pas aussi des default dans chacun des switch avec, soit un exit (quand c'est pas normal) ou un "... not implemented" pour quand on n'a pas mis toutes les valeurs ?

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("Size of this header:  \t%d\n",header.e_ehsize);
Incorrect en test

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("Start of section headers :  \t%d\n",header.e_shoff);
Incorrect en test

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("Nombre of section header: \t%d\n",header.e_shnum);
Incorrect en test

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("Section header string table index : \t%d",header.e_shstrndx);
Incorrect en test

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("\nVersion ABI : \t%d (",header.e_version);
Incorrect en test

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +        printf("0x%x ", header.e_ident[i]);
Pour afficher le nombre magique, on peut enlever le 0x avant

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("OS/ABI : \t");
D'après readelf
![image](https://user-images.githubusercontent.com/73246085/208188823-b8a445a0-b55b-4d67-bd22-a624e27df140.png)

D'après la méthode
![image](https://user-images.githubusercontent.com/73246085/208188965-437c67df-2273-463b-881d-88c49c042a99.png)

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("Version ABI : \t%d (", header.e_version);
Après vérification, ABI version c'est e_ident[EI_ABIVERSION] et pas e_version (e_version == e_ident[EI_VERSION])

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("OS/ABI : \t");
Pour la version, voir prochain commentaire

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("OS/ABI : \t");
Pour le OS/ABI c'est correct

2022-12-16 21:46 UTC, ZPyrolink commented on elfFile.c
> +    printf("OS/ABI : \t");
Pour le type, c'est aussi bon :
```c
#define ET_DYN		3		/* Shared object file */
```
Peut-être changer les valeurs prints ?

2022-12-16 21:50 UTC, ZPyrolink commented
@mhamadhajj Tu peux aussi régler le conflit en enlevant le include <stdio.h>

2022-12-19 09:05 UTC, ZPyrolink requested changes

2022-12-19 09:05 UTC, ZPyrolink commented on elfFile.c
> +    printf("ABI Version : \t%d",header.e_ident[EI_VERSION]);
Voir https://github.com/KatSukiFireStar/L3_Info_Groupe_15_Projet_Prog5/pull/21#discussion_r1051169242

2022-12-19 09:08 UTC, KatSukiFireStar approved these changes

2022-12-19 09:08 UTC, ZPyrolink approved these changes

2022-12-19 10:45 UTC, merged